name: 'Build Images'

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:

  # generate a list of dockerfiles.
  find-dirs:
    runs-on: "ubuntu-latest"
    outputs:
      dockerfile: ${{ steps.GenerateList.outputs.dockerfile }}
    steps:   
      - name: Checkout
        uses: actions/checkout@v4
      - name: GenerateList
        id: GenerateList
        run: |
          DOCKERFILES=""
          for d in ./**/Dockerfile
          do
            DOCKERFILE='"'${d/\/Dockerfile/}'"'
            if [[ $DOCKERFILES == "" ]]
            then
              DOCKERFILES=$DOCKERFILE
            else
              DOCKERFILES=$DOCKERFILES,\ $DOCKERFILE
            fi
          done
          DOCKERFILES=\{\"dockerfile\"\:\ \[$DOCKERFILES\]\}

          echo "dockerfile=$DOCKERFILES" >> "$GITHUB_OUTPUT"

          echo "dockerfile=$DOCKERFILES"
      - name: outputsss
        run: echo ${{ steps.GenerateList }}
          
  build:
    runs-on: "ubuntu-latest"
    needs: find-dirs
    if: 'always()'
    
    strategy:
      matrix: ${{ fromJson(needs.find-dirs.outputs.dockerfile) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build-Docker
        run: docker build ${{ matrix.dockerfile }}
